### ISSUE TITLE
Time consuming saving

### ISSUE THREAD

**Issue by ucc-bookkeeper** [superhawk610/ucc-portal#3]
Having to save and close over and over again; getting in and out of entering new information is time consuming (Refresh does not work without save and close first)...

**Comment by superhawk610** [comment]
The Refresh button just refreshed the list of Refiner Lots displayed in the dropdown to the left - it's been removed because its function was confusing and has been replaced by a change listener to the Refiner dropdown. The Save button at the bottom of modals on lots.php now functions as would be expected, just saving and refreshing the current view. The dropup arrow next to it will allow you to access the old behavior, Save and Close.
